version: "3.8"
services:
    hangman:
        build: ./
        ports:
        - target: 5000
          protocol: tcp
        environment:
            DATABASE_URI: 'mysql+etc:blah'
        container_name: hangman
    mysql:
        image: mysql:5.7
        ports:
        - target: 3306
          protocol: tcp
        volumes :
        - type: volume
          source: hangman
          target: /var/lib/mysql
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password123
    nginx:
        image: nginx:latest
        volumes:
        - type: bind
          source: ./nginx.conf
          target: /etc/nginx/nginx.conf
        ports:
        - target: 80
          protocol: tcp
          published: 80
volumes:
    hangman:


